'''
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''
ans = []

for a in range(2, 101):
    for b in range(2, 101):
        if a ** b not in ans:
            ans.append(a**b)

print(ans)
print(len(ans))